title: Ludivine ROBERT
description: 
author: Ludivine ROBERT
avatar: /photo.png
email: 

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate

paginate: 10

# Uncomment the below line and set the tracking ID for enabling Google Analytics
# 
# google_analytics: 

# Uncomment the below lines and set the Disqus shortname for enabling Disqus
# 
# disqus:

# Jekyll
# ======
exclude:
  - scripts/
  - README.md
  - jekyll-theme-hamilton.gemspec

# Jekyll SEO Tag (Optional)
# =========================
logo: photo.jpeg
social:
  name: Ludivine ROBERT
  links:
    - https://www.linkedin.com/in/ludivinerobert3
    - https://github.com/LudivineRobert
google_site_verification:
lang: fr
